/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "primary": "#372d8a",
        "surface-container-high": "#e8e8e7",
        "tertiary-fixed": "#ffdcbd",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#f1f1f0",
        "outline-variant": "#c8c4d3",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#693c00",
        "tertiary": "#5a3300",
        "surface": "#FFFFFF",
        "danger-offensive": "#993C1D",
        "on-primary-fixed-variant": "#423995",
        "error": "#ba1a1a",
        "surface-tint": "#5a52af",
        "warning-mid": "#854F0B",
        "secondary-fixed-dim": "#c8c5d1",
        "secondary": "#5f5d67",
        "surface-container": "#eeeeed",
        "inverse-surface": "#2f3130",
        "background": "#f9f9f8",
        "on-secondary-fixed-variant": "#47464f",
        "surface-container-low": "#f3f4f3",
        "border-strong": "#D1CFC8",
        "on-tertiary-fixed": "#2c1600",
        "on-primary-container": "#c7c1ff",
        "on-secondary-fixed": "#1b1b23",
        "surface-variant": "#e2e2e2",
        "secondary-container": "#e2deea",
        "on-error-container": "#93000a",
        "outline": "#787583",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#e4dfff",
        "tertiary-fixed-dim": "#ffb86e",
        "accent-soft": "#EEEDFE",
        "on-tertiary-container": "#ffb970",
        "on-surface-variant": "#474552",
        "text-secondary": "#6B6A72",
        "primary-container": "#4f46a3",
        "surface-bright": "#f9f9f8",
        "tertiary-container": "#7a4700",
        "on-background": "#1a1c1c",
        "surface-hover": "#FAFAF9",
        "on-surface": "#1a1c1c",
        "secondary-fixed": "#e5e1ed",
        "success-defensive": "#0F6E56",
        "text-muted": "#9B9AA0",
        "primary-fixed-dim": "#c6c0ff",
        "on-secondary-container": "#63616c",
        "surface-dim": "#dadad9",
        "inverse-primary": "#c6c0ff",
        "border-subtle": "#E3E1DC",
        "on-primary-fixed": "#150066",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#e2e2e2"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "section-margin": "2rem",
        "grid-gap": "1rem",
        "card-padding": "1.25rem",
        "stack-md": "1rem",
        "stack-sm": "0.5rem"
      },
      "fontFamily": {
        "headline-md": ["Hanken Grotesk"],
        "label-md": ["JetBrains Mono"],
        "body-md": ["Inter"],
        "headline-lg": ["Hanken Grotesk"],
        "body-lg": ["Inter"],
        "body-sm": ["Inter"],
        "label-sm": ["JetBrains Mono"],
        "headline-lg-mobile": ["Hanken Grotesk"],
        "headline-sm": ["Hanken Grotesk"]
      },
      "fontSize": {
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-lg": ["30px", { "lineHeight": "36px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-sm": ["12px", { "lineHeight": "18px", "fontWeight": "400" }],
        "label-sm": ["10px", { "lineHeight": "14px", "letterSpacing": "0.04em", "fontWeight": "500" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "30px", "fontWeight": "600" }],
        "headline-sm": ["18px", { "lineHeight": "24px", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
